apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: container-kit-redis
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: redis-operator
      version: 0.21.2
      sourceRef:
        kind: HelmRepository
        name: container-kit-redis
        namespace: flux-system
  values:
    # Add custom values here if needed, example:
    redisExporter:
      enabled: false
      image: quay.io/opstree/redis-exporter:1.0
      imagePullPolicy: Always
