---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
