apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
spec:
  instances: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
  enableSuperuserAccess: true
  storage:
    size: 512Mi  # Only if supported by your StorageClass
