apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-store
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 1                 # single-node, so replica 1
  dataPool:
    replicated:
      size: 1
  gateway:
    port: 80                  # internal service port
    securePort: 443           # optional SSL
    instances: 1              # single gateway pod
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"