kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: topolvm-provisioner-thin
  dataSourceRef:
    name: my-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
spec:
  containers:
    - name: pause
      image: ubuntu:22.04
      command:
        - bash
        - -c
        - |
          sleep infinity
      volumeMounts:
        - mountPath: /data
          name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: my-pvc2